/**
 * Navigation Provider
 *
 * Provides navigation configuration to the Shell via React Context.
 * Loads navigation.json (generated by Platform or customized for self-hosted).
 *
 * @module @mozaiks/shell/providers/NavigationProvider
 */

import React, { createContext, useContext, useState, useEffect } from 'react';

const NavigationContext = createContext(null);

/**
 * Default navigation configuration (fallback if no navigation.json exists)
 */
const DEFAULT_NAVIGATION = {
  version: '1.0.0',
  routes: [
    {
      path: '/',
      component: 'ChatPage',
      exact: true,
      meta: {
        title: 'Chat',
        requiresAuth: false
      }
    }
  ],
  sidebar: {
    items: []
  },
  topNav: {
    items: []
  }
};

/**
 * Hook to access navigation configuration
 * @returns {Object} Navigation context value
 */
export const useNavigation = () => {
  const context = useContext(NavigationContext);
  if (!context) {
    throw new Error('useNavigation must be used within a NavigationProvider');
  }
  return context;
};

/**
 * NavigationProvider Component
 *
 * Provides navigation configuration to the application.
 * Supports both static JSON and dynamic configuration loading.
 *
 * @param {Object} props
 * @param {React.ReactNode} props.children - Child components
 * @param {Object} props.config - Optional static navigation config (overrides JSON loading)
 * @param {string} props.configPath - Path to navigation.json (default: '/navigation.json')
 * @param {Function} props.onLoad - Callback when navigation is loaded
 * @param {Function} props.onError - Callback on loading error
 */
export const NavigationProvider = ({
  children,
  config = null,
  configPath = '/navigation.json',
  onLoad = () => {},
  onError = () => {}
}) => {
  const [navigation, setNavigation] = useState(config || DEFAULT_NAVIGATION);
  const [loading, setLoading] = useState(!config);
  const [error, setError] = useState(null);

  useEffect(() => {
    // If static config provided, skip loading
    if (config) {
      setNavigation(config);
      setLoading(false);
      onLoad(config);
      return;
    }

    const loadNavigation = async () => {
      try {
        const response = await fetch(configPath);

        if (!response.ok) {
          // If navigation.json doesn't exist, use defaults (common for self-hosted)
          if (response.status === 404) {
            console.log('[NavigationProvider] No navigation.json found, using defaults');
            setNavigation(DEFAULT_NAVIGATION);
            setLoading(false);
            onLoad(DEFAULT_NAVIGATION);
            return;
          }
          throw new Error(`Failed to load navigation config: ${response.status}`);
        }

        const navConfig = await response.json();

        // Validate required fields
        if (!navConfig.version || !navConfig.routes) {
          throw new Error('Invalid navigation config: missing required fields');
        }

        setNavigation(navConfig);
        setLoading(false);
        onLoad(navConfig);

        if (process.env.NODE_ENV === 'development') {
          console.log('[NavigationProvider] Loaded navigation config:', navConfig);
        }
      } catch (err) {
        console.error('[NavigationProvider] Error loading navigation:', err);
        setError(err);
        setNavigation(DEFAULT_NAVIGATION);
        setLoading(false);
        onError(err);
      }
    };

    loadNavigation();
  }, [config, configPath, onLoad, onError]);

  /**
   * Get routes from navigation config
   * @returns {Array} Route configurations
   */
  const getRoutes = () => navigation.routes || [];

  /**
   * Get sidebar items
   * @returns {Array} Sidebar navigation items
   */
  const getSidebarItems = () => navigation.sidebar?.items || [];

  /**
   * Get top navigation items
   * @returns {Array} Top navigation items
   */
  const getTopNavItems = () => navigation.topNav?.items || [];

  /**
   * Find a route by path
   * @param {string} path - Route path to find
   * @returns {Object|null} Route configuration or null
   */
  const findRoute = (path) => {
    return navigation.routes?.find(route => route.path === path) || null;
  };

  /**
   * Check if a route requires authentication
   * @param {string} path - Route path
   * @returns {boolean}
   */
  const routeRequiresAuth = (path) => {
    const route = findRoute(path);
    return route?.meta?.requiresAuth ?? false;
  };

  const contextValue = {
    // State
    navigation,
    loading,
    error,

    // Config version
    version: navigation.version,

    // Getters
    getRoutes,
    getSidebarItems,
    getTopNavItems,
    findRoute,
    routeRequiresAuth,

    // Raw config access
    routes: navigation.routes || [],
    sidebar: navigation.sidebar || { items: [] },
    topNav: navigation.topNav || { items: [] }
  };

  return (
    <NavigationContext.Provider value={contextValue}>
      {children}
    </NavigationContext.Provider>
  );
};

export default NavigationProvider;
